language: java
env:
  global:
    - VERIFY_USE_PUBLIC_BINARIES=true
    - secure: qtjlAyHNvF//hsfZMGxHdkss3vo/y69eOeopn7zkoITVZJlBhBXQ4+jVEeExghIxXyV36zQPUWCyxhqyo5haRDbG/tRnapSdTMY+i6Awdm9TqxYw1KlUTwoevXGzbqK2lxnchp8ZE7+ebEorQkAfII+FX496IqWEjzx5UbmAem+xCNdv76t9LWcW+gXLTei+i0U/s1Vr5M5aIseb8hfriE6zqood0s7S9zbydZbyhR2ky3mknVjsgMT8a8bkWN3xq9Eg3odmepXb8OZxgjmYa8rBDrS2Qz+KZOeWE3Ap1Sqo5OSA6X6ysIrbbY3zIy1oNZdsu1xHXFmVJAFSyp0c8SNIVhfIuycPw8vKQQuQELvrFoGBN2m9fL3aeuedZ4c6dc/Ok9Lrr5RE2sBaaXTUTsntO9mcYOuVCScIFpLqboZJ9minNVgvk/bv8+AkbEToBIu2RA9SmnH4szuaB3SsPGmj5ukMXuT3LO6Kpr7yYzxsNlzg5e0+C9smJ4a5ZeCRedazqwUSvZ/bWvAfMNlstlGbG5u6o4WDfQeyztZjuwUeNjHY85Iu1/SzKp8kPKPNGeAMoFWNmFiUEhjji4SeF8240dcV/u68E3LnlJV0DSL2a0vwMJTfgML3Z5gYfQWAP7OqTQglNy3oVs5GQ9zvsso1qm4n9fxhF7YbQIf3zAo=
    - secure: "hIW2/4kos6DNDizuv+ZQm1ROaG+5b+lLjZbxTPZHDap0LcuCLn2S9LMnDvg+ok7KGrzJmMGGexYW2MCAEptBEIM+TcuAqzn4PktYojqcspcrXrhrZ8HR9VJtU8NfOEmwVtYun6f0Nqb32s/+T6xGBY+DemCd+XD36H/PCX+rSZ55orshykulhwvaWLaP50L9Zb8g6atX98fChOd6HRW7O43nI+uto1c4uaC5xiOC6F+MUYG3f2v1VmOge9f0iQYn4irUlFzRIemgoMyTKISoi8kMHXWu5zZu7sGob7kG9mw/btM72XtZ75u/uaDZimTOyaiumEg72DbLsTgd8TpYbzFQTgSmAFKPYDimAEMEhch3JrSVgpX/OrfLDpNheBBfK7z0m/wOPOqzxADMUshMzLW8frlEwQ2z9iMarBsXmchNy/7YWvA6yqpVCZLx0KnWe/M/AEPnOZlYeEpoIpj/gGv8Pfkw+JdsXhgmk9JMYXP/FmA5WTCEm8fW5PuR3tBVNEQEXdc5p9J/ZWEA3LcSrFoE5BxQiZiGS7NYYID/SAlsllrEAwqnxX5B3VBvC096BHEXPg+ZwG1eDW80sK84flrVa68A/mdC20AomM6hwMDbHBLSp6nQIsm9xT9iKexSZRQ2MJwoSkFa7UIrd/LOy/YpCqaQz1H/OtvF/Q2wU4o="

jdk:
  - openjdk11

before_install: npm install -g snyk

script:
  - ./gradlew check
  - snyk/test.sh

after_success: snyk/monitor.sh

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
after_success:
  - "./gradlew jacocoRootReport"
  - curl -LSs -o codacy-coverage-reporter-assembly.jar $(curl -LSs https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest | jq -r '.assets | map({content_type, browser_download_url} | select(.content_type | contains("java-archive"))) | .[0].browser_download_url')
  - java -jar codacy-coverage-reporter-assembly.jar report -l Java -r build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml
