server:
  applicationConnectors:
    - type: http
      port: 8080
  requestLog:
    type: classic
    appenders:
      - type: access-logstash-console
serviceInfo:
  name: config
userHubSessionDuration: 150m
rootDataDirectory: ${CONFIG_DATA_PATH}
# for whatever reason this path is relative to the one above
translationsDirectory: ../../display-locales/transactions
logging:
  level: ${LOG_LEVEL:-INFO}
  appenders:
    - type: logstash-console
    - type: sentry
      dsn: ${SENTRY_DSN}
      environment: ${SENTRY_ENV}
      threshold: ERROR
      tags: {"service-name": "config"}
# these DEPLOYMENT environment variables should get
# interpolated by dropwizard
clientTrustStoreConfiguration:
  path: /tmp/truststores/${DEPLOYMENT}/ca_certs.ts
  password: puppet
rpTrustStoreConfiguration:
  path: /tmp/truststores/${DEPLOYMENT}/rp_ca_certs.ts
  password: puppet
certificateExpiryDateCheckServiceConfiguration:
  enable: true
certificateOcspRevocationStatusCheckServiceConfiguration:
  enable: true
selfService:
  enabled: ${SELF_SERVICE_ENABLED:-false}
  s3BucketName: ${SERVICES_METADATA_BUCKET:-}
  s3ObjectKey: ${METADATA_OBJECT_KEY:-}
  cacheExpiry: 30s
eidasDisabledAfter: ${EIDAS_DISABLED_AFTER:-}